# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77be543ad4a3089805b25da4f3d805ccf98ba05a2cf66f94769832333e5def670c6673fad2b99af2980fb4f5ace494441049c6af5caeb468e2c151c76371cf0c

test:
  secret_key_base: 5d0d27c70dfce142cca4f435b281be720d905f2c27b6794923318feae22531a9175ae68bca230797ec0226efa93a365f17464d45d5d2d366d9a60956b008abea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
